### ISSUE TITLE
[Test] RecentGames 조회 test파일작성

### ISSUE THREAD

**Issue by ManOfDemosan** [Dr-Pong/dr_pong_web_server#136]
## Detail

GET /users/{nickname}/records?count={count}&lastGameId={lastGameId}
## Todo
정상케이스
- [x] count 가 없는 경우 디폴트 작동확인
- [ ] lastGameId 가 없는 경우 디폴트 작동확인
- [ ] count 가 INT_MAX 인 경우
- [ ] lastGameId가  INT_MAX인 경우

Error Case
- [ ] 닉네임이 없는경우
