### ISSUE TITLE
[Refactor] Controller &Controller Test 파일 분리 

### ISSUE THREAD

**Issue by ManOfDemosan** [Dr-Pong/dr_pong_web_server#145]
## Desc

컨트롤러 기능별로 파일 분리 및 폴더 생성
테스트 파일중 컨트롤러 테스트 파일의 기능별로 파일 분리 및 폴더 생성
## Todo
- [ ]  컨트롤러 테스트 폴더생성
- [ ]  컨트롤러 테스트  기능별로 파일 분리
- [ ] 컨트롤러 폴더생성
- [ ] 컨트롤러 기능별로 파일분리
