### ISSUE TITLE
[Test / Contorller] UserRecords Controller 테스트 파일 작성

### ISSUE THREAD

**Issue by ManOfDemosan** [Dr-Pong/dr_pong_web_server#159]
## Desc

GET /users/{nickname}/records/{gameId}

## Todo
- [x] 필수 속성이 있는지 확인 (duration, me, you, rounds)
- [x] gameId가 유저가 가지고 있는경우
- [x] 나의 닉네임이 gameId에 없는 경우 예외처리 404 
- [x] 찾는 gameId가 없는 경우 예외처리 404
