### ISSUE TITLE
[Test / Service] 유저 업적 수정

### ISSUE THREAD

**Issue by ManOfDemosan** [Dr-Pong/dr_pong_web_server#17]
## Desc
유저 업적 수정요청에 대한 테스트 코드 작성

## Todo
- [ ] 정상적으로 요청이왔을때 (isSelected 가 false 인 1~3개의 업적요청)
- [ ] 정상적으로 요청이왔을때 2(isSelected 가 true & false 인 1~3개의 업적요청)
- [ ] 비정상적으로 요청이 왔을때 (userAcheivement 배열이 아닌 테이블이 들어올때)
- [ ] 비정상적으로 요청이 왔을때2 (userAcheivement 에 존재하지 않는 테이블의 인덱스에 접근)
