### ISSUE TITLE
[Refactor / Controller] Patch Controller에 jwt token적용

### ISSUE THREAD

**Issue by ManOfDemosan** [Dr-Pong/dr_pong_web_server#171]
## Desc

컨트롤러 테스트 파일에서 jwt 토큰 적용하기
req 함수 테스터 파일에 적용
Get users/images Controller 구현 하기
## Todo
- [x]  jwt 토큰 적용하기
- [x] req 함수 테스터 파일에 적용
- [x] Get users/images Controller 구현 하기
