### ISSUE TITLE
[Test / Service ] 유저 이모지 테스트 파일

### ISSUE THREAD

**Issue by ManOfDemosan** [Dr-Pong/dr_pong_web_server#20]
## Desc
이모지 get patch요청에 대한 테스트 파일 작성

## Todo
- [x] 정상적으로 요청이왔을때 (isSelected 가 false 인 1~4개의 이모지요청)
- [x] 정상적으로 요청이왔을때 2(isSelected 가 true & false 인 1~4개의 이모지요청)
- [x] 비정상적으로 요청이 왔을때 (Emojis 배열이 아닌 테이블이 들어올때)
- [x] 비정상적으로 요청이 왔을때2 (Emojis 에 존재하지 않는 테이블의 인덱스에 접근)
