### ISSUE TITLE
[Refactor] module 리팩토링

### ISSUE THREAD

**Issue by ManOfDemosan** [Dr-Pong/dr_pong_web_server#226]
## Desc

모듈들을 각각 import 하는것이 아니라 
레포지토리 모듈, 서비스 모듈을 생성해서 
한방에 import 해서 사용하는 방향으로 리팩토링

## Todo
- [ ] provider 디렉토리 생성
- [ ] repository 모듈 생성
- [ ] service 모듈 생성
- [ ] 각각의 모듈을 적용
