### ISSUE TITLE
[Test ] AuthModule JWT 작동 테스트

### ISSUE THREAD

**Issue by nheo9143** [Dr-Pong/dr_pong_web_server#23]
## Desc

- AuthModule JWT 기반 유저 조회 테스트
## Detail

- AuthModule 유저 조회 로직 테스트코드 작성

## Todo
- [x] AuthModule JWT 기반 유저 조회 테스트코드 작성
    - [ ] (추가) nickname 설정 안한 경우 테스트코드에 추가
- [x] AuthModule 유저 조회 로직 테스트코드 동작 확인
