### ISSUE TITLE
[Test] 유저 전적 조회 테스트

### ISSUE THREAD

**Issue by ManOfDemosan** [Dr-Pong/dr_pong_web_server#28]
## Desc
유저전적 조회 테스트 파일 작성

## Detail
get 요청이 오면 2가지 서비스 로직이 실행됨
1. 유저의 전체 게임 데이터 반환
2. 유저의 현시즌 랭크데이터 + 현시즌 best랭크 데이터

## Todo
- [ ] 유저 전체 게임 데이터 반환 테스트
- [ ] 유저 현시즌 랭크 데이터 반환 테스트
- [ ] 유저 현시즌 최고점 랭크 데이터 반환 테스트
