### ISSUE TITLE
[Feat / API ] 유저 타이틀 정보 조회 

### ISSUE THREAD

**Issue by ManOfDemosan** [Dr-Pong/dr_pong_web_server#3]
## Desc
유저에 해당하는 서비스와 컨트롤러 추가

## Todo

- Api 구현
    - [ ] 'GET' /users/{nickname}/titles
        - [ ] 메인 조회 로직 구현
        - [ ] 에러 처리 구현
