### ISSUE TITLE
[Test / Api] User Controller 내부 api 테스트코드 작성

### ISSUE THREAD

**Issue by nheo9143** [Dr-Pong/dr_pong_web_server#44]
## Desc

-  users controller 내부 api 테스트코드 작성
## Todo
- [x] GET /users/{nickname}/detail
- [x] GET /users/{nickname}/stat
- [x] GET /users/{nickname}/achievements?selected={true}
- [x] GET /users/{nickname}/achievements?selected={false}
- [x] GET /users/{nickname}/emojis?selected={true}
- [x] GET /users/{nickname}/emojis?selected={false}
- [x] GET /users/{nickname}/titles
- [x] PATCH /users/{nickname}/detail
- [x] PATCH /users/{nickname}/achievements
- [x] PATCH /users/{nickname}/emojis
