### ISSUE TITLE
[Fix / Api] 유저 기본 정보 조회, 수정 구현 및 테스트

### ISSUE THREAD

**Issue by ManOfDemosan** [Dr-Pong/dr_pong_web_server#8]
## Desc
하나의 API 요청을 역할에 따라 분리

## Detail
PATCH, GET 요청을 확장성과 독립성을 위하여 분리함

## Todo
- [x] Get요청 테스트코드 구현
- [x] 유저 기본 정보 조회 분할 구현 
- [x] Patch 테스트코드 구현
- [x] 유저의 정보 수정 분할구현
